name: Test
on:
- push
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.9]
    name: Check py${{ matrix.python }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - run: pip install -U twine setuptools wheel ninst scikit-build
    - run: PATHTOOLS=$HOME/NiftyPET_tools python setup.py sdist
    - run: twine check dist/*
  test:
    runs-on: [self-hosted, cuda]
    name: Test
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: pip install -U -e .[dev]
    - run: pytest
    - run: codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
