name: Test
on:
- push
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.9]
    name: Check py${{ matrix.python }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: set PYSHA
      run: echo "PYSHA=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PYSHA }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: pip install -U pre-commit twine setuptools wheel setuptools_scm[toml] ninst scikit-build
    - run: PATHTOOLS=$HOME/NiftyPET_tools python setup.py sdist
    - run: twine check dist/*
    - run: pre-commit run -a --show-diff-on-failure
  test:
    runs-on: [self-hosted, cuda]
    name: Test
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: pip install -U -e .[dev]
    - run: pytest
    - run: codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  deploy:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [check, test]
    name: PyPI Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install -U twine setuptools wheel setuptools_scm[toml] ninst scikit-build
    - run: PATHTOOLS=$HOME/NiftyPET_tools python setup.py sdist
    - run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        skip_existing: true
    - id: collect_assets
      name: Collect assets
      run: |
        echo "::set-output name=asset_path::$(ls dist/*.tar.gz)"
        echo "::set-output name=asset_name::$(basename dist/*.tar.gz)"
        git log --pretty='format:%d%n- %s%n%b---' $(git tag --sort=v:refname | tail -n2 | head -n1)..HEAD > _CHANGES.md
    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: nimpa ${{ github.ref }} beta
        body_path: _CHANGES.md
        draft: true
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.collect_assets.outputs.asset_path }}
        asset_name: ${{ steps.collect_assets.outputs.asset_name }}
        asset_content_type: application/gzip
